# Generated by Django 4.0 on 2022-01-27 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carton',
            fields=[
                ('carton_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('production_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('distributor_scan_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('pharmacist_details', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_scan', models.IntegerField(blank=True, default=0, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('number_of_scan', models.IntegerField(blank=True, default=0, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('carton_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.carton')),
            ],
        ),
    ]
