# Generated by Django 4.0 on 2022-01-27 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carton',
            name='delivery_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery', to='userManagement.deliveryperson'),
        ),
        migrations.AddField(
            model_name='carton',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='distributor', to='userManagement.distributor'),
        ),
        migrations.AddField(
            model_name='carton',
            name='manufacturer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userManagement.manufacturer'),
        ),
    ]
